<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <OutputType>Library</OutputType>
    <RootNamespace>Bortle.NINA.Emitter</RootNamespace>
    <AssemblyName>Emitter</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CloudNative.CloudEvents" Version="2.9.0" />
    <PackageReference Include="CloudNative.CloudEvents.SystemTextJson" Version="2.9.0" />
    <PackageReference Include="NATS.Net" Version="3.1.0" />
    <PackageReference Include="NINA.Plugin" Version="3.2.0.9001" />
  </ItemGroup>
  <Import Project="NINAPlugin.targets" />
</Project>