name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test --no-build
